name: eshop-stack

services:
  eshopdb:
    container_name: eshopdb
    environment:
         POSTGRES_DB: EshopDb
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
    restart: always
    ports: 
          -  "5432:5432"  
    volumes:
            - postgresql_eshopdb:/var/lib/postgresql

  seq: 
    container_name: seq
    environment:
         ACCEPT_EULA: Y
         SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    restart: always
    ports:
          -  "5341:5341"
          -  "9091:80" 
