services:
  eshopdb:
      image: postgres:latest

  distributedcache:
      image: redis:latest
  seq:
      image: datalust/seq:latest

  messagebus:
      image: rabbitmq:management    

  identity:
      image: quay.io/keycloak/keycloak:latest
      
volumes:
    postgresql_eshopdb: